services:
  rabbit:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    networks:
      - waffle
  configserver:
    image: kodomochi/configserver:v2
    container_name: configserver-microservice
    ports:
      - "8071:8071"
    depends_on:
      rabbit:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - waffle
    environment:
      SPRING_RABBITMQ_HOST: "rabbit"
  accounts:
    image: kodomochi/accounts:v2
    container_name: account-microservice
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - waffle
    environment:
      SPRING_APPLICATION_NAME: accounts
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: uat # default, dev, uat, prod
      SPRING_RABBITMQ_HOST: "rabbit"
  loans:
    image: kodomochi/loans:v2
    container_name: loans-microservice
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - waffle
    environment:
      SPRING_APPLICATION_NAME: loans
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: uat # default, dev, uat, prod
      SPRING_RABBITMQ_HOST: "rabbit"
  cards:
    image: kodomochi/card:v2
    container_name: cards-microservice
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - waffle
    environment:
      SPRING_APPLICATION_NAME: card
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: uat # default, dev, uat, prod
      SPRING_RABBITMQ_HOST: "rabbit"
networks:
  waffle:
    driver: "bridge"