services:
  accounts:
    image: kodomochi/accounts:v1
    container_name: account-microservice
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - waffle
  loans:
    image: kodomochi/loans:v1
    container_name: loans-microservice
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - waffle
  cards:
    image: kodomochi/card:v1
    container_name: cards-microservice
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - waffle

networks:
  waffle:
    driver: "bridge"